name = ELD
description = A simple 3 column layout for ELD, based on Omega Simple layout
template = eld-layout

; Regions
regions[header]         = Header
regions[content_upper]  = Content upper region
regions[content_middle] = Content middle region (default)
regions[content_lower]  = Content lower region
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

