<?php


/** 
 * Implementation of hook_block_info(). 
 */
function linked_image_block_block_info() { 
	$blocks['linked_image'] = array(
	    'info' => t('Linked image'), 
	  );
	return $blocks;
}

/** 
 * Implementation of hook_block_view(). 
 */
function linked_image_block_block_view($delta = '') { 
	switch ($delta) {
		case 0:
		
			// TODO put these values in config variables
			$img_path = base_path().drupal_get_path('theme', variable_get('theme_default', NULL)).'/images/eld.gif';
			$link_url = 'http://eliterature.org';
			
			$block['content'] = '<a href="'.$link_url.'"><img src="'.$img_path.'" /></a>';
			$block['subject'] = ''; // Don't show a block title
  		return $block;
	}
}

// TODO provide themeing overrides (see https://www.drupal.org/node/933976)
